markdown: rdiscount
permalink: /:title.html
auto: true
relative_permalinks: false

safe: true
lsi: false
pygments: true

name: ITIN.ua
description: Все об IT Бизнесе - Собираем знания вместе

admin_email: ivan.ivanenko@gmail.com
book_date: 2015-07-23 00:00:00

url: http://itin.com.ua

all_countries:
- id: poland
  name: Польша

- id: denmark
  name: Дания

- id: germany
  name: Германия

- id: latvia
  name: Латвия

- id: thailand
  name: Тайланд

- id: norway
  name: Норвегия

- id: netherlands
  name: Нидерланды

all_categories:
- id: a1
  name: Работа с иностранными компаниями
  url: rabota-s-inostrannimi-kompaniyami.html

- id: a2
  name: Организация бизнеса в Украине
  url: organizatsiya-biznessa-v-ukraine.html

- id: a3
  name: Деятельность предпринимателей
  url: deyatelnost-predprinimatelei.html

- id: a4
  name: Защита прав интеллектуальной собственности
  url: zaschita-prav-intellektualnoi-sobstvennosti.html

authors:
  ivan-ivanenko:
    name: Ivan Ivanenko
    job: Программист сайта itin.ua
    image: Ivan.png
    fb: https://www.facebook.com/ivan1.ivanenko
    ln: https://www.linkedin.com/profile/view?id=12440410
    tw:
    g_:
    web: http://foobnix.com
    git: https://github.com/foobnix

  anna-ivanenko:
    name: Анна Иваненко
    job: Юрист
    image: anya.jpg

  katerina-timchenko:
    name: Катерина Тимченко
    job: Юрист
    image: katerina-timchenko.jpg
    fb: https://www.facebook.com/ktimchenko
    ln: https://www.linkedin.com/profile/view?id=42676613&trk=nav_responsive_tab_profile
    tw:
    g_:
    web: http://timchenko.kiev.ua

  katerina-britskaya:
    name: Катерина Брицкая
    job: Юрист
    image: katerina-britskaya.jpg
    web: http://www.laudis.ua/
    
  tak-audit:
    name: Так-аудит
    job: Аудит
    image: tak_audit.jpg
    fb: 
    ln: 
    tw:
    g_:
    web: 
    git: 
    
  tatyana-zhila:
    name: Татьяна Жила
    job: Патентный поверенный
    image: tatyana-zhila.jpg
    fb: 
    ln: 
    tw:
    g_:
    web: http://www.laudis.ua/
    git: 
    

